server:
  port: 9090
config:
  server:
    url: 192.168.99.100:9080
    auth: c29tYXM6cGFzc3dvcmQ=

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/