version: '2'
services:
  discovery-server:
    image: config-mgmt/discovery-server
    expose:
      - "8761"
    ports:
      - "8761:8761"
  config_server:
    image: config-mgmt/config-server
    ports:
      - "9080:9080"
    links:
      - postgres
      - discovery-server
  postgres:
    image: postgres:9.5
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_config
  config_client:
    image: config-mgmt/config-client
    expose:
      - "9090"
    ports:
      - "9090:9090"
    links:
      - discovery-server
      - config_server


