config_server:
  image: config-mgmt/config-server
  ports:
    - "9080:9080"
  links:
    - postgres
postgres:
  image: postgres:9.5
  expose:
    - "5432"
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: password123
    POSTGRES_DB: db_config
